"""Auto-commit and push new reports to GitHub for Pages publishing.

Called by the cta-daily orchestrator as the final step of the pipeline.
Only stages/commits the output/ directory — source-code changes stay separate.

Usage:
    python publish.py
    python publish.py --dry-run    # show what would be published, no actual push
"""
from __future__ import annotations

import subprocess
import sys
import io
from datetime import date
from pathlib import Path

if sys.stdout.encoding != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

REPO = Path(__file__).parent


def _run(cmd: list[str]) -> tuple[int, str]:
    r = subprocess.run(
        cmd, cwd=REPO,
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    return r.returncode, (r.stdout + r.stderr).strip()


def main() -> int:
    dry = "--dry-run" in sys.argv
    print("=" * 60)
    print(f"  CTA Auto-Publish {'(dry run)' if dry else ''}")
    print("=" * 60)

    # 1. Are there changes in output/?
    code, out = _run(["git", "status", "--porcelain", "output/"])
    if code != 0:
        print(f"[ERROR] git status failed:\n{out}")
        return 1
    if not out.strip():
        print("\n  No report changes in output/. Nothing to publish.")
        return 0

    print("\n  Changes detected:")
    for line in out.splitlines():
        print(f"    {line}")

    if dry:
        print("\n  (dry run — no commit/push)")
        return 0

    # 2. Stage
    code, out = _run(["git", "add", "output/"])
    if code != 0:
        print(f"\n[ERROR] git add failed:\n{out}")
        return 1

    # 3. Commit
    today = date.today().isoformat()
    msg = (
        f"report: CTA daily {today}\n\n"
        f"Auto-generated by cta-daily orchestrator.\n\n"
        f"Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"
    )
    code, out = _run(["git", "commit", "-m", msg])
    if code != 0:
        # Could be "nothing to commit" if only whitespace/mode changes slipped in
        print(f"\n[WARN] git commit returned {code}:\n{out}")
        if "nothing to commit" in out:
            return 0
        return 1
    print(f"\n  Committed: {today}")

    # 4. Push
    print("\n  Pushing to origin main ...")
    code, out = _run(["git", "push", "origin", "main"])
    if code != 0:
        print(f"\n[ERROR] git push failed:\n{out}")
        print(
            "\n  Commit preserved locally. Resolve auth/network and run:\n"
            "    git push origin main"
        )
        return 1

    print("\n  ✓ Published to GitHub Pages.")
    print("  Visit: https://mark00lui.github.io/Stock_U_turn/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
